### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by xyIsHere** [HPAI-BSC/AtomDetection_ACSTEM#1]
Dear authors,

Thanks for your great work. Recently, I'm working on a similar problem. Could you provide the link to the corresponding publication? It will be very helpful to understand code. 

Thanks in advance!

**Comment by dariogarcia** [comment]
Hi @xyIsHere ,
the paper is currently under review. Once its published we will add the reference to this repo.

**Comment by xyIsHere** [comment]
> Hi @xyIsHere , the paper is currently under review. Once its published we will add the reference to this repo.

Thanks!

**Comment by dariogarcia** [comment]
For the record, README updated with link: https://pubs.acs.org/doi/10.1021/jacs.1c12466 @xyIsHere
